### ISSUE TITLE
Improving the maintenance of this project

### ISSUE THREAD

**Issue by technosophos** [deislabs/libcnab-rust#14]
We'd like to get this project operating a little more smoothly, getting it toward a release-quality library (instead of a highly experimental one as it is today).

@jlegrone and @glyn: Are you too interested in helping with the ongoing core maintainership of this repo?

**Comment by glyn** [comment]
Yes, please count me in. I've worked with Rust in the past and am happy to at least review PRs.

**Comment by technosophos** [comment]
Should we create a CODEOWNERS file like the one we have on the other projects? Seems to be a nice point of reference for who is responsible.
