### ISSUE TITLE
Naming conventions for crates

### ISSUE THREAD

**Issue by radu-matei** [deislabs/libcnab-rust#15]
> Crate names should not use `-rs` or `-rust` as a suffix or prefix. Every crate is Rust! It serves no purpose to remind users of this constantly.

Coming from the [Rust Language Nursery Documentation](https://rust-lang-nursery.github.io/api-guidelines/naming.html).

Should we rename this crate to simply `libcnab`?

**Comment by jlegrone** [comment]
The crate (as it will be viewed on crates.io) is named libcnab already 😄 

https://github.com/deislabs/libcnab-rust/blob/4ca3f231d1cd16ef2afdeb4f49569dd440ddbc48/Cargo.toml#L2

In 40bcc6c71b7df4806722f285201788c610e3feeb I added some cargo metadata, so we should be ready to publish an initial version when we think it's time.

**Comment by jlegrone** [comment]
I've also exchanged some emails with @genedna recently (the owner of [crates.io/crates/cnab](https://crates.io/crates/cnab)) and he's interested in collaborating. Would we be in favor of switching to the `cnab` crate name and transferring ownership to Deis on crates.io?

**Comment by radu-matei** [comment]
Oh, silly me.. this should be closed, thanks!
