### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by jdolitsky** [deislabs/libcnab-rust#6]
I don't know much about rust, how do I build this thang?

**Comment by jlegrone** [comment]
1. Install rust tooling: https://doc.rust-lang.org/cargo/getting-started/installation.html
2. Clone repo and `cargo build`/`cargo test`: https://doc.rust-lang.org/cargo/guide/working-on-an-existing-project.html

[`cargo doc --open`](https://doc.rust-lang.org/cargo/commands/cargo-doc.html) is also super useful. 😄

**Comment by radu-matei** [comment]
While most Rust projects seem to use Cargo to build and test, without going through a Makefile first, this should probably at least be documented.

Closing this issue, but opened #17 to track the documentation aspect - feel free to reopen if you think we should really add a Makefile.
Thanks!
